name: 'Test'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt-get install unzip -y
          mkdir local/bin
          curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=local/bin sh
      - name: Run tests
        run: local/bin/deno test